[book]
title = "Prayers for SEiN"
authors = ["Yuan-Wei Pi"]
description = "This is a prayer space for SEiN."

[rust]
edition = "2018"

[output.html]
no-section-label = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2